Repository SkillsFundingAgency/das-payments-V2, pull requests merged in 2019-06, with the labels that each got.

#404 Release/release pr 397 pr 398
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/Learner.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/Price.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/Training.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Services/UkprnService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/FM36Base.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/Framework403Learner.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/Framework593Learner.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/IlrDcService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/LearnerExtensions.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/LearnerMutatorFactory.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/LearnerRequest.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/NonLevy/BasicDay/Framework593LearnerWithdrawsAfterPlannedEndDate.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/NonLevy/BasicDay/Framework593LearnerWithdrawsAfterQualifyingPeriod.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/NonLevy/SmallEmployer/Framework403LearnerWithEHCPlanAndSmallEmployer.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Mapping/IlrProfile.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/SFA.DAS.Payments.AcceptanceTests.EndToEnd.csproj
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Additional Payments English and Maths/Non-levy learner taking single Level 1 aim, progressing to and completing single Level 2 aim, completes to time PV2-387.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Disadvantaged Uplift/Non-Levy-On Framework-Disadvantage Uplift 1-10-paid-PV2-435.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner/Small Employer/Non-Levy 19-24 learner with EHC plan with a small employer at start PV2-328.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/packages.config
  src/SFA.DAS.Payments.AcceptanceTests.Services/BespokeHttpClient/BespokeHttpClient.cs
  src/SFA.DAS.Payments.AcceptanceTests.Services/BespokeHttpClient/IBespokeHttpClient.cs
  src/SFA.DAS.Payments.AcceptanceTests.Services/Intefaces/IJobService.cs
  src/SFA.DAS.Payments.AcceptanceTests.Services/Services/JobService.cs
Labels: Release/Release_PR_397_PR_398

#406 Release/release pv2 843 pv2 676 pv2 1074 pv2 1014
  src/SFA.DAS.Payments.AcceptanceTests.Core/Automation/TestSession.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Helpers/ApprenticeshipHelper.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy - Data Locks/PV2-676 - DLOCK08 when multiple matching record found for the agreed price.feature
  src/SFA.DAS.Payments.Application/Data/Configurations/ApprenticeshipDuplicateModelConfiguration.cs
  src/SFA.DAS.Payments.Application/Repositories/IPaymentsDataContext.cs
  src/SFA.DAS.Payments.Application/Repositories/PaymentsDataContext.cs
  src/SFA.DAS.Payments.DataLocks.Application.UnitTets/Cache/DataLockLearnerCacheTest.cs
  src/SFA.DAS.Payments.DataLocks.Application/Cache/DataLockLearnerCache.cs
  src/SFA.DAS.Payments.DataLocks.Application/Infrastructure/ioc/DataLockModule.cs
  src/SFA.DAS.Payments.DataLocks.Application/Repositories/ApprenticeshipRepository.cs
  src/SFA.DAS.Payments.DataLocks.DataLockService.UnitTests/GivenADataLockService/WhenCallingHandlePayment.cs
  src/SFA.DAS.Payments.DataLocks.DataLockService/DataLockService.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CalculatePeriodStartAndEndDateTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/CourseValidatorsProcessorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/MultipleLearnersValidatorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/OnProgrammeStoppedValidatorTests.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Infrastructure/CacheKeys.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Models/DataLockValidationModel.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CalculatePeriodStartAndEndDate.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/MultipleLearnersValidator.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/OnProgrammePeriodsValidationProcessor.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/OnProgrammeStoppedValidator.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/ICalculatePeriodStartAndEndDate.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/IDataLockLearnerCache.cs
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.ApprenticeshipDuplicate.sql
  src/SFA.DAS.Payments.Database/SFA.DAS.Payments.Database.sqlproj
  src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/MappingTest.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/FunctionalSkillsEarningValueResolver.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/MappingExtensions.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/OnProgrammeEarningValueResolver.cs
  src/SFA.DAS.Payments.Model.Core/Entities/ApprenticeshipDuplicateModel.cs
Labels: Release/Release_PV2-843_PV2_676_PV2_1074_PV2_1014

#409 Release/release pv2 1017 pv2 256
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/SFA.DAS.Payments.AcceptanceTests.EndToEnd.csproj
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Employer Change of Circumstances/16-18 Learner, changes employer, earns incentive payment in the transfer month at a date before the transfer date- PV2-372.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/E2E - PV2-256a - Levy standard learner, price is changed, orginally mix funded and a negative amount is left to be paid.feature
  src/SFA.DAS.Payments.RequiredPayments.Application.UnitTests/Application/Processors/ApprenticeshipContractType2EarningEventProcessorTest.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Infrastructure/Ioc/RequiredPaymentsModule.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Processors/ApprenticeshipContractType2EarningEventProcessor.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Processors/ApprenticeshipContractTypeEarningEventProcessor.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Processors/EarningEventProcessorBase.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Processors/FunctionalSkillEarningsEventProcessor.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Processors/PayableEarningEventProcessor.cs
  src/SFA.DAS.Payments.RequiredPayments.Domain.UnitTests/Services/NegativeEarningsServiceTests.cs
  src/SFA.DAS.Payments.RequiredPayments.Domain/Interfaces/INegativeEarningService.cs
  src/SFA.DAS.Payments.RequiredPayments.Domain/Services/NegativeEarningsService.cs
Labels: Release/Release_PV2-1017_PV2-256

#411 Release/release pv2 1009 pv2 740 transfers
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/SFA.DAS.Payments.AcceptanceTests.EndToEnd.csproj
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Transfers/E2E - PV2-740 - Single Levy learner paid partialy via transfer, own levy and co-funding.feature
  src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Service/RequiredLevyAmountFundingSourceServiceTest.cs
  src/SFA.DAS.Payments.FundingSource.Application/Infrastructure/CacheKeys.cs
  src/SFA.DAS.Payments.FundingSource.Application/Infrastructure/Configuration/AutoMapperConfigurationFactory.cs
  src/SFA.DAS.Payments.FundingSource.Application/Infrastructure/ioc/FundingSourceModule.cs
  src/SFA.DAS.Payments.FundingSource.Application/Interfaces/IRequiredLevyAmountFundingSourceService.cs
  src/SFA.DAS.Payments.FundingSource.Application/SFA.DAS.Payments.FundingSource.Application.csproj
  src/SFA.DAS.Payments.FundingSource.Application/Services/RequiredLevyAmountFundingSourceService.cs
  src/SFA.DAS.Payments.FundingSource.Domain/Interface/ILevyBalanceService.cs
  src/SFA.DAS.Payments.FundingSource.Domain/Services/LevyBalanceService.cs
  src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/Handlers/CalculatedRequiredLevyAmountHandler.cs
  src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/Handlers/MonthEndCommandHandler.cs
  src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/Handlers/UnableToFundTransferFundingSourcePaymentEventHandler.cs
  src/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces/ILevyFundedService.cs
  src/SFA.DAS.Payments.FundingSource.LevyFundedService/LevyFundedService.cs
  src/SFA.DAS.Payments.FundingSource.Messages/Commands/ProcessUnableToFundTransferFundingSourcePayment.cs
  src/SFA.DAS.Payments.FundingSource.Messages/Events/UnableToFundTransferFundingSourcePaymentEvent.cs
Labels: Release/Release_PV2-1009_PV2-740-Transfers

#412 Release/release pv2 1084 earnings integration
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.DataLocks.DataLockProxyService/Handlers/ApprenticeshipContractType1EarningEventHandler.cs
  src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/Act1MappingTest.cs
  src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/MappingTest.cs
  src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/SubmittedLearnerAimBuilderTest.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Handlers/ProcessLearnerHandler.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/IncentiveEarningValueResolver.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/IntermediateLearningAim.cs
Labels: Release/Release_PV2-1084_earnings_Integration

#444 Release/release pv2 1115 1157
  src/SFA.DAS.Payments.AcceptanceTests.Core/Automation/TestSession.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/Configurations/ProviderModelConfiguration.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Infrastructure/BindingBootstrapper.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/SFA.DAS.Payments.AcceptanceTests.Core.csproj
  src/SFA.DAS.Payments.AcceptanceTests.Core/Services/RandomUkprnService.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Services/UkprnService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/FM36Base.cs
  src/SFA.DAS.Payments.Datalocks.Messages/Events/EmployerChangedProviderPriority.cs
  src/SFA.DAS.Payments.PerformanceTests/EndToEndPerformanceTests.cs
Labels: Release/Release_PV2_1115_1157

#430 Create EmployerChangedProviderPriority class
  src/SFA.DAS.Payments.Datalocks.Messages/Events/EmployerChangedProviderPriority.cs
Labels: Release/Release_PV2_1115_1157

#441 PDI-95 Fixed issue with invalid date in ILR
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/FM36Base.cs
Labels: Release/Release_PV2_1115_1157

#450 Release/release pdi 25 29 40 51
  src/SFA.DAS.Payments.AcceptanceTests.Core/SFA.DAS.Payments.AcceptanceTests.Core.csproj
  src/SFA.DAS.Payments.AcceptanceTests.Core/Services/IIlrService.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Services/IlrNullService.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/packages.config
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Infrastructure/FeatureScopedBootstrapper.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/FM36Base.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/Framework593Learner.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/IlrDcService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/LearnerMutatorFactory.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/NonLevy/BasicDay/Framework593LearnerWithdrawsAfterPlannedEndDate.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/NonLevy/BasicDay/Framework593LearnerWithdrawsAfterQualifyingPeriod.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/SFA.DAS.Payments.AcceptanceTests.EndToEnd.csproj
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/RefundsSteps.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Additional Payments English and Maths/Non-levy learner taking single Level 1 aim, progressing to and completing single Level 2 aim, completes to time PV2-387.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Disadvantaged Uplift/Non-Levy-On-Framework-Disadvantage-Uplift 21-27-paid-PV2-437.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-levy standard learner, payments made then price is changed retrospectively from beginning PV2-258.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/packages.config
Labels: Release/Release_PDI_25_29_40_51
