Repository SkillsFundingAgency/das-payments-V2, pull requests merged in 2019-09, with the labels that each got.

#667 Release/release pv2 949 pv2 1443 pv2 1421 fixes for e2 e test and datalock
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Infrastructure/BindingBootstrapper.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ApprovalsInterfaceSteps.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.DataLocks.Application/Infrastructure/ioc/DataLockModule.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/EarningPeriodsValidationProcessorTests.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/StartDateValidatorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/EarningPeriodsValidationProcessor.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/StartDateValidator.cs
  src/SFA.DAS.Payments.FundingSource.AcceptanceTests/Steps/FundingSourceSteps.cs
Labels: DataLock, Release

#654 pv2-949 Fix of Entity Framework issue relating to ReportingFundingAimLineType on Payment entity.
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
Labels: DataLock

#534 PV2-1208 Added aim sequence number to the EarningEvent table
  src/SFA.DAS.Payments.Model.Core/Audit/EarningEventModel.cs
Labels: DataLock

#656 PV2-1448: updated index to cover removed learner query
  src/SFA.DAS.Payments.Database/Payments2/Tables/SubmittedLearnerAim.sql
Labels: DataLock

#677 Release/release pv2 1464 v2
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/SFA.DAS.Payments.AcceptanceTests.EndToEnd.csproj
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy - Data Locks/PV2-1464_Ignore_Apprenticeship_That_Stop_Within_A_Day_Of_Starting.feature
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/EarningPeriodsValidationProcessorTests.cs
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/MultipleLearnersValidatorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/EarningPeriodsValidationProcessor.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/MultipleLearnersValidator.cs
  src/SFA.DAS.Payments.RequiredPayments.ServiceFabric/ApplicationPackageRoot/ApplicationManifest.xml
Labels: DataLock, Release

#681 Added ukprn filter and increase CommandTimeout - PV2-1458
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/TestOrchestrator.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/VerificationService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Scripts/DataStoreQuery.sql
Labels: Release

#687 Release/release pv2 1471 1473
  src/SFA.DAS.Payments.AcceptanceTests.Core/Automation/DcHelper.cs
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Employer Change of Circumstances/PV2-621 Learner changes employer,16wk gap between commitments, provider is paid for the first 12wk of gap.feature
  src/SFA.DAS.Payments.ProviderPayments.AcceptanceTests/Steps/BindingBootstrapper.cs
Labels: Release

#631 PDI-158 work for 295
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/LearnerMutatorFactory.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Learner Change of Circumstances/Levy learner changes price during month - PV2-295.feature
Labels: Integration

#632 PDI-162_Changes_for_339
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/LearnerMutators/LearnerMutatorFactory.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Inconsistent Submission Data/PV2-339 Levy learner - change in aim sequence number.feature
Labels: Integration

#690 PV2_1480 - When Duplicate Apprenticeship Is Same Ukprn Return No DataLockErrors
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/MultipleLearnersValidatorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/MultipleLearnersValidator.cs
Labels: Release

#682 Release/release pv2 1025 1323 1482 1485
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ApprovalsInterfaceSteps.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndSteps.cs
  src/SFA.DAS.Payments.Application/Data/Configurations/PaymentModelConfiguration.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/PeriodisedEventMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/RequiredPayments/LevyRequiredPaymentMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application/Data/PaymentsEventModelDataTable.cs
  src/SFA.DAS.Payments.Audit.Application/Data/PeriodisedPaymentsEventModelDataTable.cs
  src/SFA.DAS.Payments.Audit.Application/Mapping/EarningEvents/EarningEventProfile.cs
  src/SFA.DAS.Payments.Audit.Application/Mapping/MappingExtensions.cs
  src/SFA.DAS.Payments.Audit.Model/PeriodisedPaymentsEventModel.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/EarningsEventProfile.cs
  src/SFA.DAS.Payments.FundingSource.Application.UnitTests/Mapper/CalculatedRequiredLevyAmountMapperTest.cs
  src/SFA.DAS.Payments.FundingSource.Application/Infrastructure/Configuration/AutoMapperConfigurationFactory.cs
  src/SFA.DAS.Payments.Messages.Core/Events/IPeriodisedPaymentEvent.cs
  src/SFA.DAS.Payments.Messages.Core/Events/PeriodisedPaymentEvent.cs
  src/SFA.DAS.Payments.Model.Core/Audit/PaymentsEventModel.cs
  src/SFA.DAS.Payments.Model.Core/Entities/PaymentModel.cs
  src/SFA.DAS.Payments.Model.Core/LearningAim.cs
  src/SFA.DAS.Payments.ProviderPayments.Application.UnitTests/Mapping/FundingSourceToPaymentEventMappingTests.cs
  src/SFA.DAS.Payments.ProviderPayments.Application/Data/ProviderPaymentDataTable.cs
  src/SFA.DAS.Payments.ProviderPayments.Application/Mapping/ProviderPaymentsProfile.cs
  src/SFA.DAS.Payments.RequiredPayments.Application/Mapping/RequiredPaymentsProfile.cs
  src/SFA.DAS.Payments.RequiredPayments.Messages/Events/CalculatedRequiredLevyAmount.cs
  src/SFA.DAS.Payments.RequiredPayments.Model/Entities/PaymentHistoryEntity.cs
Labels: Release

#689 PV2-1481 - View of the Payments v2 Database for DC Data Match Report
  src/SFA.DAS.Payments.Database/Payments2/Views/Payments2.DataMatchReport.sql
  src/SFA.DAS.Payments.Database/SFA.DAS.Payments.Database.sqlproj
Labels: In-Test, Release

#695 Release/release 1463 1489
  src/Parallel.runsettings
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Helpers/ApprenticeshipHelper.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Properties/AssemblyInfo.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ApprovalsInterfaceSteps.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.Application/Repositories/PaymentsDataContext.cs
  src/SFA.DAS.Payments.sln
Labels: Back to Dev, Release

#693 PV2-1489 clear old apprenticeships by ULN
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ApprovalsInterfaceSteps.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
Labels: In-Test

#703 Release/release pv2 1419 19 sep
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/DataLock/DataLockEventMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/DataLock/EarningFailedDataLockMatchingMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/DataLock/FunctionalSkillDataLockEventMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/DataLock/FunctionalSkillEarningFailedDataLockMatchingMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/DataLock/PayableEarningEventMappingTests.cs
  src/SFA.DAS.Payments.Audit.Application.UnitTests/Mapping/DataLock/PayableFunctionalSkillEarningEventMappingTests.cs
  src/SFA.DAS.Payments.DataLocks.Application.UnitTets/Mapping/MapperConfigurationTest.cs
  src/SFA.DAS.Payments.Datalocks.Messages/Events/EarningFailedDataLockMatching.cs
  src/SFA.DAS.Payments.Datalocks.Messages/Events/PayableEarningEvent.cs
  src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/MappingTest.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/EarningsEventProfile.cs
  src/SFA.DAS.Payments.EarningEvents.Messages/Events/ApprenticeshipContractTypeEarningsEvent.cs
  src/SFA.DAS.Payments.ProviderPayments.Application.UnitTests/Mapping/FundingSourceToPaymentEventMappingTests.cs
Labels: Release

#702 Release/Release_PV2_1494
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/MultipleLearnersValidatorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/MultipleLearnersValidator.cs
Labels: Release

#699 PV2-1494_Switch-off the DLOCK_08 functionality for latest release into Model Office
  src/SFA.DAS.Payments.DataLocks.Domain.UnitTests/Services/CourseValidation/MultipleLearnersValidatorTest.cs
  src/SFA.DAS.Payments.DataLocks.Domain/Services/CourseValidation/MultipleLearnersValidator.cs
Labels: In-Test

#706 Release/release pv2 1484
  src/SFA.DAS.Payments.EarningEvents.Application.UnitTests/Mapping/ApprenticeshipContractTypeEarningsEventBuilderTest.cs
  src/SFA.DAS.Payments.EarningEvents.Application/Mapping/ApprenticeshipContractTypeEarningsEventBuilder.cs
  src/SFA.DAS.Payments.EarningEvents.Domain.UnitTests/LearnerEarningsTests.cs
  src/SFA.DAS.Payments.EarningEvents.Domain.UnitTests/SFA.DAS.Payments.EarningEvents.Domain.UnitTests.csproj
  src/SFA.DAS.Payments.EarningEvents.Domain/LearnerSubmissionProcessor.cs
  src/SFA.DAS.Payments.EarningEvents.EarningEventsService/PackageRoot/Config/Settings.xml
  src/SFA.DAS.Payments.EarningEvents.ServiceFabric/ApplicationPackageRoot/ApplicationManifest.xml
  src/SFA.DAS.Payments.EarningEvents.ServiceFabric/ApplicationParameters/Cloud.xml
Labels: Release

#705 Pv2 1484 allow different payment configurations
  src/Parallel.runsettings
  src/SFA.DAS.Payments.AcceptanceTests.Core/Data/TestPaymentsDataContext.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Helpers/ApprenticeshipHelper.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Properties/AssemblyInfo.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/ApprovalsInterfaceSteps.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Steps/EndToEndStepsBase.cs
  src/SFA.DAS.Payments.Application/Repositories/PaymentsDataContext.cs
  src/SFA.DAS.Payments.sln
Labels: In-Test

#709 Release/release 1171 1261
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/2 learners 2 employers 1 provider enough levy - PV2-267.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finished late PV2-274.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finishes on time PV2-261.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finishes one month early PV2-275.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finishes two months early PV2-276.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, no levy available, finishes on time PV2-262.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One levy learner finishes on time not enough levy to cover full payment-PV2-266.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two Learners two employers one provider not enough levy - PV2-268.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two levy learners but only enough levy to fund one learner- PV2-264.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two levy learners one employer but two providers and enough levy PV2-269.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two levy learners one employer but two providers not enough levy_PV2-270.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Non-Levy learner continuing 12 months earnings PV2-615.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Non-levy learner - learning support OPP and completion payments - PV2-429.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Non-levy learner withdraws after planned end date PV2-278.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner Finishes Late PV2-336.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner Withdraws After Qualifying Period PV2-277.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner finishes early balancing and completion payments made PV2-335.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner finishes on time completion payment made PV2-334.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner submitted late PV2-427.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Two Non Levy-Learners One Finishes Late And Other Finishes Early PV2-199.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Two Non-Levy Learners Finish On Time PV2-337.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-Levy standard learner, price is changed and a negative amount is left to be paid - results in a refund PV2-255.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-levy learner provider retrospectively notifies a withdrawal - PV2-251.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-levy standard learner, payments made then price is changed retrospectively from beginning PV2-258.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/E2E - PV2-256a - Levy standard learner, price is changed, orginally mix funded and a negative amount is left to be paid.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy learner changes start date forwards in month - PV2-280.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy learner insufficient levy available to cover full payments provider retrospectively notifies of a withdrawal PV2-252.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy learner, levy available, 2 providers - one provider retrospectively notifies a withdrawal need to be refunded PV2-253.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner changes start date backwards in month - PV2-281.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner price change from start - PV2-259.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner price change with negative earning - PV2-257.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner retrospective withdrawl - PV2-250.feature
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.ProviderAdjustmentPayments.sql
  src/SFA.DAS.Payments.Database/SFA.DAS.Payments.Database.sqlproj
Labels: Release

#698 Added earning adjustment statement table PV2-1171
  src/SFA.DAS.Payments.Database/Payments2/Views/Payments2.DataMatchReport.sql
  src/SFA.DAS.Payments.Database/SFA.DAS.Payments.Database.sqlproj
Labels: In-Test

#668 PV2-1261 - Add @basic_day and @basic_refund tags to SpecFlow tests
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/2 learners 2 employers 1 provider enough levy - PV2-267.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finished late PV2-274.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finishes on time PV2-261.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finishes one month early PV2-275.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, levy available, finishes two months early PV2-276.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One Levy Learner, no levy available, finishes on time PV2-262.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/One levy learner finishes on time not enough levy to cover full payment-PV2-266.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two Learners two employers one provider not enough levy - PV2-268.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two levy learners but only enough levy to fund one learner- PV2-264.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two levy learners one employer but two providers and enough levy PV2-269.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy Learner/Basic Day/Two levy learners one employer but two providers not enough levy_PV2-270.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Non-Levy learner continuing 12 months earnings PV2-615.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Non-levy learner - learning support OPP and completion payments - PV2-429.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Non-levy learner withdraws after planned end date PV2-278.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner Finishes Late PV2-336.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner Withdraws After Qualifying Period PV2-277.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner finishes early balancing and completion payments made PV2-335.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner finishes on time completion payment made PV2-334.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/One Non-Levy Learner submitted late PV2-427.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Two Non Levy-Learners One Finishes Late And Other Finishes Early PV2-199.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Basic Day/Two Non-Levy Learners Finish On Time PV2-337.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-Levy standard learner, price is changed and a negative amount is left to be paid - results in a refund PV2-255.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-levy learner provider retrospectively notifies a withdrawal - PV2-251.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Non-Levy Learner - Refunds/Non-levy standard learner, payments made then price is changed retrospectively from beginning PV2-258.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/E2E - PV2-256a - Levy standard learner, price is changed, orginally mix funded and a negative amount is left to be paid.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy learner changes start date forwards in month - PV2-280.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy learner insufficient levy available to cover full payments provider retrospectively notifies of a withdrawal PV2-252.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy learner, levy available, 2 providers - one provider retrospectively notifies a withdrawal need to be refunded PV2-253.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner changes start date backwards in month - PV2-281.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner price change from start - PV2-259.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner price change with negative earning - PV2-257.feature
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Refunds/Levy-learner retrospective withdrawl - PV2-250.feature
Labels: In-Test

#711 Release/release pv2 1468 1476
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/App.Release.config
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/ETEVerificationTests.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/Configuration.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/FileHelpers.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/SubmissionService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/TestOrchestrator.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/TestSettings.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Infrastructure/VerificationService.cs
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification.csproj
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Scripts/EarningsCte.sql
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Scripts/EarningsDetail.sql
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Scripts/EarningsSummary.sql
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/Scripts/PaymentsQuery.sql
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd.Verification/app.config
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Inconsistent Submission Data/PV2-284 Levy learner, adds English and Maths aim after payments made.feature
Labels: Passed, Release

#714 Release/release pv2 1483 v2
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Data/AuditDataContext.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Data/Entities/DataLockEvent.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Data/Entities/DataLockEventNonPayablePeriod.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Data/Entities/DataLockEventNonPayablePeriodFailures.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Data/Entities/DataLockEventPriceEpisode.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Data/Entities/DataLockPayablePeriod.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/DataLock/Clean Up Data Lock Events On Submission Success.feature
  src/SFA.DAS.Payments.Audit.AcceptanceTests/DataLock/Clean Up Data Lock Events.feature
  src/SFA.DAS.Payments.Audit.AcceptanceTests/DataLock/DataLockSteps.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/DataLock/SubmissionData.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Infrastructure/BindingBootstrapper.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/Infrastructure/EndpointNames.cs
  src/SFA.DAS.Payments.Audit.AcceptanceTests/SFA.DAS.Payments.Audit.AcceptanceTests.csproj
  src/SFA.DAS.Payments.Audit.AcceptanceTests/app.config
  src/SFA.DAS.Payments.Audit.AcceptanceTests/packages.config
  src/SFA.DAS.Payments.Audit.Application.UnitTests/DataLock/SubmissionEventProcessorTest.cs
  src/SFA.DAS.Payments.Audit.Application/Data/DataLockEventRepository.cs
  src/SFA.DAS.Payments.Audit.Application/Infrastructure/Ioc/AuditModule.cs
  src/SFA.DAS.Payments.Audit.Application/PaymentsEventProcessing/DataLock/SubmissionEventProcessor.cs
  src/SFA.DAS.Payments.Audit.Application/SFA.DAS.Payments.Audit.Application.csproj
  src/SFA.DAS.Payments.Audit.DatalockService/Handlers/SubmissionFailedEventHandler.cs
  src/SFA.DAS.Payments.Audit.DatalockService/Handlers/SubmissionSucceededEventHandler.cs
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.DataLockEvent.sql
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.DataLockEventNonPayablePeriod.sql
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.DataLockEventNonPayablePeriodFailures.sql
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.DataLockEventPayablePeriod.sql
  src/SFA.DAS.Payments.Database/Payments2/Tables/Payments2.DataLockEventPriceEpisode.sql
Labels: Release

#719 Release/release pv2 1500
  src/SFA.DAS.Payments.AcceptanceTests.Core/SFA.DAS.Payments.AcceptanceTests.Core.csproj
  src/SFA.DAS.Payments.AcceptanceTests.Core/packages.config
  src/SFA.DAS.Payments.EarningEvents.Application/SFA.DAS.Payments.EarningEvents.Application.csproj
  src/SFA.DAS.Payments.JobContextMessageHandling/SFA.DAS.Payments.JobContextMessageHandling.csproj
  src/SFA.DAS.Payments.PeriodEnd.Application/SFA.DAS.Payments.PeriodEnd.Application.csproj
  src/SFA.DAS.Payments.PeriodEnd.PeriodEndService/SFA.DAS.Payments.PeriodEnd.PeriodEndService.csproj
Labels: Release

#721 PV2-1494_Switch-off_DLOCK_08_Acceptance_TEST
  src/SFA.DAS.Payments.AcceptanceTests.EndToEnd/Tests/Levy - Data Locks/PV2-676 - DLOCK08 when multiple matching record found for the agreed price.feature
Labels: Passed
